FROM python:3.9

WORKDIR /app

# Usar el nombre correcto del archivo de requerimientos
COPY requirements_app.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY app/main.py .
COPY app/model.pkl .

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]