name: CI/CD API Penguin

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install -r api/requirements_app.txt
          pip install scikit-learn pandas joblib
        
      - name: Train model
        run: |
          cd api
          python train_model.py

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push API image
        run: |
          docker build -t johnsanchez27/penguin-api:latest -f api/Dockerfile_app ./api
          docker push johnsanchez27/penguin-api:latest
